# Generated by Django 3.2.16 on 2025-09-06 16:39

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='type', chained_model_field='type', on_delete=django.db.models.deletion.PROTECT, related_name='cashflows', to='dds.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.PROTECT, related_name='cashflows', to='dds.subcategory', verbose_name='Подкатегория'),
        ),
    ]
