# Generated by Django 3.2.16 on 2025-09-06 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0002_auto_20250906_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания записи'),
        ),
    ]
